services:
  - type: web
    name: sports-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: ONESIGNAL_APP_ID
        value: "tu-app-id-de-onesignal"
      - key: ONESIGNAL_API_KEY
        value: "tu-api-key-de-onesignal"
      - key: FOOTBALL_API_KEY
        value: "04d73dd17729e5edb6408c2e826009ab"
